# Generated by Django 3.2.8 on 2022-06-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_course_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(default=0, help_text='Lesson order or position'),
        ),
        migrations.AlterIndexTogether(
            name='lesson',
            index_together={('course', 'title')},
        ),
    ]
